name: tests

on:
    push:
        branches:
            - main

jobs:
    test:
        name: run tests
        runs-on: ubuntu-20.04

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: start redis
              run: |
                  docker-compose up -d redis
            - name: wait for redis
              run: |
                  ./support/wait.sh
            - name: tests
              run: |
                  ./support/test.sh ./about
